# Generated by Django 5.2.17 on 2026-08-26 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=30, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("DIRECT", "مستقیم"), ("OVERHEAD", "سربار")],
                        default="DIRECT",
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(max_length=120)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=18)),
                ("date", models.DateField()),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "ثبت\u200cشده"),
                            ("CANCELLED", "ابطال\u200cشده"),
                        ],
                        default="REGISTERED",
                        max_length=10,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paid_from",
                    models.ForeignKey(
                        help_text="حساب صندوق/بانک",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses_paid",
                        to="accounting.account",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="core.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "هزینه",
                "verbose_name_plural": "هزینه\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=30, unique=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("RECEIPT", "دریافت"), ("PAYMENT", "پرداخت")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=18)),
                ("date", models.DateField()),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "ثبت\u200cشده"),
                            ("CANCELLED", "ابطال\u200cشده"),
                        ],
                        default="REGISTERED",
                        max_length=10,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="حساب صندوق/بانک",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="accounting.account",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="core.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "دریافت/پرداخت",
                "verbose_name_plural": "دریافت\u200cها و پرداخت\u200cها",
                "ordering": ["-created_at"],
            },
        ),
    ]
