# Generated by Django 5.2.17 on 2026-09-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Daran X", max_length=120)),
                (
                    "brand_sub",
                    models.CharField(
                        default="شرکت فناوری اطلاعات داران", max_length=160
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("phone1", models.CharField(blank=True, max_length=40)),
                ("phone2", models.CharField(blank=True, max_length=40)),
                ("mobile", models.CharField(blank=True, max_length=40)),
                ("email", models.CharField(blank=True, max_length=120)),
                ("website", models.CharField(blank=True, max_length=120)),
                ("economic_code", models.CharField(blank=True, max_length=40)),
                ("registration_no", models.CharField(blank=True, max_length=40)),
                ("bank_name", models.CharField(blank=True, max_length=80)),
                ("bank_branch", models.CharField(blank=True, max_length=80)),
                ("bank_account", models.CharField(blank=True, max_length=40)),
                ("bank_iban", models.CharField(blank=True, max_length=40)),
                ("bank_branch_code", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "پروفایل شرکت",
                "verbose_name_plural": "پروفایل شرکت",
            },
        ),
        migrations.AddField(
            model_name="party",
            name="registration_no",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
